### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by Bubalo1234** [KitKait2001/the_otherworld#1]
Hello! I would like to help you write the wiki. I'm not the best writer, but I'm sure fast whenever you add something. Also, I can help you come up with more dialogue! I actually have experience with this, I'm an amateur game dev, and I've come up with randomized dialogue a lot in my games.

**Comment by Bubalo1234** [comment]
Also sorry if I seem over-enthusiastic, it's just that I was litterally making a similar mod when yours showed up. Mine was called Alter, and was set in a world where a war is going on between two races. I just wanna help, that's all. Also, I don't have a Mcreator account.

**Comment by KitKait2001** [comment]
Hello! Thank you for your feedback btw! : D 
I'm used to developing mods on my own, and I'm not sure if I can pay money to people to help with it. But thank you for the offer! : D
I also have a discord linked to my mod page so if you want we can work through some of the possible bugs you came across there! : )

**Comment by Bubalo1234** [comment]
no! I dont want money lol. I'm just a friendly helper person lol. plus, im too young to get a job XD

**Comment by KitKait2001** [comment]
Well I'm not too sure if I can partner because I'm more of a solo person but I'll definitely listen to suggestions and feedback, and can implement them! We can stay in contact for that! : D Also thank you for playing and testing it out! I appreciate it! 
: D
