### ISSUE TITLE
how do I make children

### ISSUE THREAD

**Issue by Bubalo1234** [KitKait2001/the_otherworld#2]
How do I make children with an Oni? im a female oni, and I've given this guy a thorned rose and a ring an now were married. how do we make children

**Comment by KitKait2001** [comment]
Hello! there is a 5 minute countdown to have kids, so when you log in you have to wait 5 minutes for it to work, along with another 5 minute cooldown after having the kid. This is just so people don't spam kids xD

**Comment by Bubalo1234** [comment]
ok but like is there a keybind or something lol

**Comment by KitKait2001** [comment]
Oh sorry! You just give them another flower lol. That's all ya need xD

**Comment by Bubalo1234** [comment]
lol :)
