### ISSUE TITLE
ores are wayyy too rare

### ISSUE THREAD

**Issue by Bubalo1234** [KitKait2001/the_otherworld#3]
I'm an oni, and ive been mining for maybe 30 minutes. I litterally cannot find any ores, except the occasional coal. please help

**Comment by KitKait2001** [comment]
I have been testing the mod and the ores seem fine on my end. How odd. They spawn at y 128 and below. Do the edges of the islands have exposed ores?

**Comment by Bubalo1234** [comment]
only coal. I've actuaklly onlmost mined this entire island out

**Comment by Bubalo1234** [comment]
and no, I dont want any money lol, I just wanna help, cause this mod feels a lot like the one I always wanted to make. I have a few ideas for maybe mob diversity and such.

**Comment by KitKait2001** [comment]
Wow that is really strange! I would like to discuss this further with you if you'd like. Do you have discord? If so you can join my server so we can see what's goin on? :/

**Comment by Bubalo1234** [comment]
hahah. I have discord, but I don't usually give out my tag to everybody. Let's talk on GitHub for now, so I can trust u and stuff. Also, my parents wont let me join servers lol. anyways, I would like to but cant. Also, I think there should be otherworld tameable mob so you can have cool pet would be nice.

**Comment by Bubalo1234** [comment]
also I was just playing around with blockbench, this is what I made
<img width="1211" alt="Screen Shot 2022-09-26 at 2 41 46 PM" src="https://user-images.githubusercontent.com/80659275/192385948-8549043f-1c05-4c93-a77a-e28023ba9bff.png">

**Comment by Bubalo1234** [comment]
one sec
[assets.zip](https://github.com/KitKait2001/the_otherworld/files/9649974/assets.zip)
